apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "MySecret"
          objectType: "secretsmanager"
          jmesPath:
              - path: "username"
                objectAlias: "MySecretUsername"
  secretObjects:
    - secretName: myk8ssecret
      type: Opaque
      data: 
        - objectName: "MySecretUsername"
          key: "username"