apiVersion: v2
name: csi-secrets-store-provider-aws
version: 0.0.1
appVersion: 1.0.r1-10-g1942553-2021.06.04.00.07-linux-amd64
kubeVersion: ">=1.17.0-0"
description: A Helm chart to install the Secrets Store CSI Driver and the AWS Key Management Service Provider inside a Kubernetes cluster.
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/secrets-store-csi-driver-provider-aws
home: https://github.com/aws/secrets-store-csi-driver-provider-aws
# I put my name because I did not know who else to insert but
# more than willingly I pass the burden and honors to someone else.
maintainers:
  - name: Pierluigi Lenoci
    email: pierluigi.lenoci@gmail.com
