name: Build Windows Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    - name: Make build
      run: make -f Makefile.win build
      shell: bash
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      env:
        repo: ghcr.io/saedx1/secrets-store-csi-driver-provider-aws
      run: |
        BASE_NAME=${{ env.repo }}:${{ github.ref_name }}
        docker build . -f Dockerfile.win --build-arg WINDOWS_VERSION=2019 --push ${BASE_NAME}-windows-2019
        docker build . -f Dockerfile.win --build-arg WINDOWS_VERSION=2022 --push ${BASE_NAME}-windows-2022

        docker manifest create ${BASE_NAME} ${BASE_NAME}-windows-2019 ${BASE_NAME}-windows-2022

        docker manifest annotate ${BASE_NAME} ${BASE_NAME}-windows-2019 --os windows --arch amd64 --os-version 10.0.17763.4645
        docker manifest annotate ${BASE_NAME} ${BASE_NAME}-windows-2022 --os windows --arch amd64 --os-version 10.0.20348.1850

        docker manifest push ${BASE_NAME}
